### PR TITLE
Do not check `reason` of the response

### PR DESCRIPTION
**Pull request by lambdalisue**
See https://github.com/LinkTed/async-http-proxy/pull/1 for the background.

### CODE REVIEW

**Comment by LinkTed** [comment]
Thanks for your contribution.

**Comment by lambdalisue** [comment]
Thanks a lot. Could you upload a new version so that I can use it through crates.io please.

**Comment by LinkTed** [comment]
New version is released `v1.2.0`.

**Comment by lambdalisue** [comment]
Thanks a lot

**Pull request merged**
